### ISSUE TITLE
MaxiNetFrontendServer: can't run after default installation.

### ISSUE THREAD

**Issue by mvanotti** [MaxiNet/MaxiNet#14]
Hi All!
I am trying out MaxiNet. I've followed the installation instructions in the webpage, and tried to run the QuickStart examples.

When I run MaxiNetFrontendServer, I get the following error:
```
mvanotti@ubuntu:~/MaxiNet/MaxiNet/FrontendServer$ MaxiNetFrontendServer 
Broadcast server running on 0.0.0.0:9091
NS running on 192.168.33.1:9090 (192.168.33.1)
URI = PYRO:Pyro.NameServer@192.168.33.1:9090
DEBUG:MaxiNet.FrontendServer.server:starting up and connecting to  192.168.33.1:9090
/usr/local/lib/python2.7/dist-packages/Pyro4-4.46-py2.7.egg/Pyro4/core.py:912: UserWarning: Class <type 'instance'> doesn't expose any methods or attributes. Did you forget setting @expose on them?
  warnings.warn("Class %r doesn't expose any methods or attributes. Did you forget setting @expose on them?" % type(obj))
Traceback (most recent call last):
  File "/usr/local/bin/MaxiNetFrontendServer", line 9, in <module>
    load_entry_point('MaxiNet==1.0', 'console_scripts', 'MaxiNetFrontendServer')()
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.0-py2.7.egg/MaxiNet/FrontendServer/server.py", line 336, in main
    MaxiNetManager().start()
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.0-py2.7.egg/MaxiNet/FrontendServer/server.py", line 183, in start
    self._pyrodaemon = Pyro4.Daemon(host=self.config.get_nameserver_ip())
  File "/usr/local/lib/python2.7/dist-packages/Pyro4-4.46-py2.7.egg/Pyro4/core.py", line 248, in __getattr__
    self._pyroGetMetadata()
  File "/usr/local/lib/python2.7/dist-packages/Pyro4-4.46-py2.7.egg/Pyro4/core.py", line 548, in _pyroGetMetadata
    self.__pyroCreateConnection()
  File "/usr/local/lib/python2.7/dist-packages/Pyro4-4.46-py2.7.egg/Pyro4/core.py", line 516, in __pyroCreateConnection
    self.__processMetadata(handshake_response["meta"])
  File "/usr/local/lib/python2.7/dist-packages/Pyro4-4.46-py2.7.egg/Pyro4/core.py", line 573, in __processMetadata
    raise errors.PyroError("remote object doesn't expose any methods or attributes. Did you forget setting @expose on them?")
Pyro4.errors.PyroError: remote object doesn't expose any methods or attributes. Did you forget setting @expose on them?
Monitoring clusters...
```

I have no idea how to fix it.
I'm running Ubuntu Server 16.04, with python 2.7.

**Comment by mvanotti** [comment]
It seems to be a problem with newer versions of Pyro4.

https://pythonhosted.org/Pyro4/servercode.html#creating-a-pyro-class-and-exposing-its-methods

Apparently, now you have to register which methods you want to expose.

**Comment by schwabe** [comment]
I commited a fix for that. My quick tests show that is working but it is possible that I missed a function.

**Comment by mvanotti** [comment]
Thanks!
