### ISSUE TITLE
does MaxiNet support CPULimitedHost?

### ISSUE THREAD

**Issue by stevelorenz** [MaxiNet/MaxiNet#17]
Hallo,

In my experiments i need the **CPULimitedHost** feature of Mininet. 

in the source code i cannot find lines about **CPULimitedHost** like

```
from mininet.node import CPULimitedHost
```

and i read from the documentation of MaxiNet, that the NodeWrapper class support **setCPUFrac** function. i try to use this for testing and AttributeError occurs.

```
Traceback (most recent call last):
  File "shell.py", line 20, in <module>
    exp.get_node('h1').setCPUFrac(0.5)
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.0-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 1559, in method
    return self._call(name, *params1, **params2)
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.0-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 1551, in _call
    return self.worker.rpc(self.nn, cmd, *params1, **params2)
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.0-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 302, in rpc
    return self.mininet.rpc(host, cmd, *params1, **params2)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 171, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 431, in _pyroInvoke
    raise data
AttributeError: 'Host' object has no attribute 'setCPUFrac'
```

Does MaxiNet support **CPULimitedHost**? and where can i set the parameter? I need to finish my student work in 3 weeks, so i hope there is a relativ quick response. Thanks so much for that.

Thanks very much for the viewing and have a nice day.

**Comment by wallaschek** [comment]
Hi,

by default MaxiNet uses the normal mininet host class which does not support cpulimiting. For MaxiNet to use a different host class you either need to supply that class to the addHost call in a dynamically created topology or adapt the calls to the Mininet class in the create_mininet function of the MininetManager class (WorkerServer) in order to supply a class to the host parameter.

Regards,
Felix

**Comment by stevelorenz** [comment]
Thanks so much for the help, i will try the second method with my forked repository.

Best regards,
Steve
