### ISSUE TITLE
unable to setup maxinet 

### ISSUE THREAD

**Issue by yogeshVU** [MaxiNet/MaxiNet#29]
My Setup:

I have one VM where I am running the fronendserver and the worker.

I am trying to start working on the maxinet by following the instructions stated in  
https://github.com/MaxiNet/MaxiNet/blob/master/INSTALL.txt#L78

I get following error:
1) 

```

ubuntu@maxinet-master-2:~/pox$ python2 pox.py forwarding.12_learning
POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
Module not found: forwarding.12_learning

```

And when running simplePing.py
```

ubuntu@maxinet-master-2:/usr/local/share/MaxiNet/examples$ ./simplePing.py
# localhost:5345 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
# localhost:5345 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
# localhost:5345 SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
Traceback (most recent call last):
  File "./simplePing.py", line 13, in <module>
    cluster = maxinet.Cluster()
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.1-py2.7.egg/MaxiNet/Fro                                                                                                                                                             ntend/maxinet.py", line 611, in __init__
    self.add_workers()
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.1-py2.7.egg/MaxiNet/Fro                                                                                                                                                             ntend/maxinet.py", line 705, in add_workers
    while self.add_worker():
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.1-py2.7.egg/MaxiNet/Fro                                                                                                                                                             ntend/maxinet.py", line 690, in add_worker
    if(self.add_worker_by_hostname(hn)):
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.1-py2.7.egg/MaxiNet/Fro                                                                                                                                                             ntend/maxinet.py", line 669, in add_worker_by_hostname
    self.worker.append(Worker(self.nameserver, pyname, self.config.get_nameserve                                                                                                                                                             r_password(), self.sshtool))
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.1-py2.7.egg/MaxiNet/Fro                                                                                                                                                             ntend/maxinet.py", line 136, in __init__
    self._fix_mtus()
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.1-py2.7.egg/MaxiNet/Fro                                                                                                                                                             ntend/maxinet.py", line 344, in _fix_mtus
    self.run_cmd("ip li se dev " + intf + " mtu 1600")
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.1-py2.7.egg/MaxiNet/Fro                                                                                                                                                             ntend/maxinet.py", line 271, in run_cmd
    return self.server.check_output(cmd)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 186, in __ca                                                                                                                                                             ll__
    return self.__send(self.__name, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 461, in _pyr                                                                                                                                                             oInvoke
    data = serializer.deserializeData(msg.data, compressed=msg.flags & message.F                                                                                                                                                             LAGS_COMPRESSED)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/util.py", line 170, in dese                                                                                                                                                             rializeData
    return self.loads(data)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/util.py", line 447, in load                                                                                                                                                             s
    return pickle.loads(data)
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subproces                                                                                                                                                             s.CalledProcessError'>, ())

```

**Comment by bluewingtan** [comment]
Hi @yogeshVU ：

I have exactly met the second problem which you mentioned in my installation of Maxinet. As @osearbhain said, your output message is truncated at the right hand side, but it doesn't matter. What your problem is misconfiguration of the `MaxiNet.cfg` file, you should like to check `FrontendServer` section and `worker` section(or what you have named), especially checking the `ip` property, while you running Maxinet in localhost, you should set `ip` to 127.0.0.1.

I hope I can help you solve this problem.

**Comment by samkopmann** [comment]
Hi @bluewingtan :
I am facing the same issue as @yogeshVU (TypeError: ('__init__() takes at least 3 arguments (1 given)') when starting an experiment.
What misconfiguration do I need to search for in the MaxiNet.cfg exactly.
I have already checked the ips, they are fine.
Thanks in advance.
