### ISSUE TITLE
SSH issue

### ISSUE THREAD

**Issue by SCoulY** [MaxiNet/MaxiNet#38]
i can SSHing from one of my Virtual Machine to another but it didn't managed to do 'ssh-keyscan -p 5345 <ip>' BTW i have added the ip and hostname to .ssh/known_hosts
`coky2@vm2:~/MaxiNet/MaxiNet/Frontend/examples$ python simplePing.py 
# 192.168.122.208 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.10
no hostkey alg
# 192.168.122.208 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.10
INFO:MaxiNet.Frontend.maxinet:added worker vm2
# 192.168.122.209 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.10
Connection closed by 192.168.122.209
Traceback (most recent call last):
  File "simplePing.py", line 14, in <module>
    cluster = maxinet.Cluster()
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 611, in __init__
    self.add_workers()
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 705, in add_workers
    while self.add_worker():
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 690, in add_worker
    if(self.add_worker_by_hostname(hn)):
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 669, in add_worker_by_hostname
    self.worker.append(Worker(self.nameserver, pyname, self.config.get_nameserver_password(), self.sshtool))
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 139, in __init__
    self.sshtool.add_known_host(self.ip())
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/tools.py", line 245, in add_known_host
    str(self.config.get_sshd_port()), ip])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['ssh-keyscan', '-p', '5345', '192.168.122.209']' returned non-zero exit status 255
INFO:MaxiNet.Frontend.maxinet:removed worker vm2`

**Comment by wallaschek** [comment]
Hi,

"no hostkey alg" hints that there was a problem generating or using the SSH host key on the worker machine. Can you enable the Debug mode (see wiki) and try again? Also, check what happens if you manually run ssh-keygen -q -N "" -t rsa -f /tmp/hostkey

Regards,
Felix
