### ISSUE TITLE
TCLink With Tunneling

### ISSUE THREAD

**Issue by Giuseppe1992** [MaxiNet/MaxiNet#50]
Hello,
I am trying to create a network with Maxinet using only TCLinks.

This is an example:

```python
from mininet.topo import Topo
from mininet.node import OVSSwitch

from MaxiNet.Frontend import maxinet
from MaxiNet.tools import Tools
import time
from mininet.link import TCLink

# create topology
topo = Topo()
ips=[]
n=30
hosts=["h"+str(i) for i in range(1,n+1)]
for i in range(1,n+1):
    topo.addHost( 'h{}'.format(i), ip=Tools.makeIP(i), mac=Tools.makeMAC(i))
    ips.append(Tools.makeIP(i))
    topo.addSwitch( 's{}'.format(i), dpid=Tools.makeDPID(i) )
    topo.addLink('h{}'.format(i),'s{}'.format(i),cls=TCLink,bw=1000)

for i in range(1,n):
    topo.addLink('s{}'.format(i), "s{}".format(i+1),cls=TCLink,bw=1000)
# start cluster
cluster = maxinet.Cluster(minWorkers=2, maxWorkers=10)

# start experiment with OVSSwitch on cluster
exp = maxinet.Experiment(cluster, topo, switch=OVSSwitch)
exp.setup()

print "waiting 5 seconds for routing algorithms on the controller to converge"
time.sleep(5)
...
exp.stop()
```
I have this error:
```bash
Traceback (most recent call last):
  File "test.py", line 63, in <module>
    exp.setup()
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 1466, in setup
    controller=self.controller)
  File "/usr/local/lib/python2.7/dist-packages/MaxiNet-1.2-py2.7.egg/MaxiNet/Frontend/maxinet.py", line 201, in start
    switch=self.switch, STT=STT)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 185, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Pyro4/core.py", line 476, in _pyroInvoke
    raise data  # if you see this in your traceback, you should probably inspect the remote traceback as well
TypeError: __init__() got multiple values for keyword argument 'node1'
```
If I don't use TCLink class it works, but of course it does not set the limits

Checking a bit maxinet code I found this documentation for the addLink function
```python
def addLink(self, node1, node2, port1=None, port2=None, cls=None,
            autoconf=False, **params):
    """Add link at runtime.

    Add link at runtime and create tunnels between workers if
    necessary. Will not work for mininet.node.UserSwitch switches.
    Be aware that tunnels will only work between switches so if you
    want to create a link using a host at one side make sure that
    both nodes are located on the same worker.
    autoconf parameter handles attach() and config calls on switches and
    hosts.

    Args:
        node1: Node name or NodeWrapper instance.
        node2: Node name or NodeWrapper instance.
        port1: Optional port number of link on node1.
        port2: Optional port number of link on node2.
        cls: Optional class to use on Link creation. Be aware that
            only mininet.link.Link and mininet.link.TCLink are
            supported for tunnels.
        autoconf: mininet requires some calls to makIe newly added
            tunnels work. If autoconf is set to True MaxiNet will
            issue these calls automatically.

    Raises:
        RuntimeError: If cls is not None or Link or TCLink and
            tunneling is needed.
    """
```

The "Raises:" is a bit confusing, but for what I can see it seems that Maxinet do not support tunneling for TCLink. 
Can you confirm?
If I am wrong how to correctly setup the network with all TCLinks?

Thank you for your time
Giuseppe

**Comment by Giuseppe1992** [comment]
It is working adding the topology in /MaxNet/Maxinet/tools.py
```python
class Linear(Topo):
    def randByte(self, max=255):
        return hex(random.randint(0, max))[2:]

    def makeMAC(self, i):
        return "00:" + self.randByte() + ":" + \
               self.randByte() + ":00:00:" + hex(i)[2:]

    def makeDPID(self, i):
        a = self.makeMAC(i)
        dp = "".join(re.findall(r'[a-f0-9]+', a))
        return "0" * (16 - len(dp)) + dp

    # args is a string defining the arguments of the topology!
    # has be to format: "x,y,z" to have x hosts and a bw limit of y for
    # those hosts each and a latency of z (in ms) per hop
    def __init__(self, hosts=2, bwlimit=10, lat=0.1, **opts):
        Topo.__init__(self, **opts)
        bw = bwlimit
        #bw = 10
        for i in range(1,hosts+1):
            h = self.addHost('h' + str(i ), mac=self.makeMAC(i),
                            ip="10.0.0." + str(i ))
            sw = self.addSwitch('s' + str(i), dpid=self.makeDPID(i),
                                **dict(listenPort=(13000 + i - 1)))
            self.addLink(h, sw,bw=bw)
        for i in range(1,hosts):
            self.addLink("s"+str(i), "s"+str(i+1),bw=bw)

```
